// Union with scoped discriminator
module Module
{
    enum ScopedEnumHelper
    {
        ENUM_VALUE_1,
        ENUM_VALUE_2,
        ENUM_VALUE_3
    };
};

union UnionScopedDiscriminator switch (Module::ScopedEnumHelper)
{
    case Module::ENUM_VALUE_1:
        long first;
    case Module::ENUM_VALUE_2:
        long long second;
    default:
        octet third;
};
