@extensibility(APPENDABLE)
struct GrandparentStruct
{
    long my_long;
};

@extensibility(APPENDABLE)
struct ParentStruct : GrandparentStruct
{
    short my_short;
    string my_string;
    GrandparentStruct my_grandparent;
};

@extensibility(APPENDABLE)
struct NestedStructElement
{
    boolean my_boolean;
};

@extensibility(APPENDABLE)
struct StructStruct : ParentStruct
{
    NestedStructElement my_nested_element;
    char my_char;
};
