
// struct InternalComplexPoints_TypeIntrospectionExample
// {
//     long x_member;
//     long y_member;
//     long z_member;
// };

struct InternalComplexMessage_TypeIntrospectionExample
{
    string message;
};

struct Complex_TypeIntrospectionExample
{
	unsigned long index;
    // InternalComplexPoints_TypeIntrospectionExample internal_data;
    InternalComplexMessage_TypeIntrospectionExample messages[3];
};
