/*************************************************************************
 * Copyright (c) 2013 eProsima. All rights reserved.
 *
 * This generated file is licensed to you under the terms described in the
 * fastcdr_LICENSE file included in this fastcdr distribution.
 *
 *************************************************************************
 * 
 * @file FilteringExamplePublisher.h
 * This header file contains the declaration of the publisher functions.
 *
 * This file was generated by the tool fastcdrgen.
 */


#ifndef _FILTERINGEXAMPLE_PUBLISHER_H_
#define _FILTERINGEXAMPLE_PUBLISHER_H_

#include <fastrtps/fastrtps_fwd.h>
#include <fastrtps/publisher/PublisherListener.h>

#include "FilteringExamplePubSubTypes.h"

using namespace eprosima::fastrtps;

class FilteringExamplePublisher 
{
public:
	FilteringExamplePublisher();
	virtual ~FilteringExamplePublisher();
	bool init();
	void run();
private:
	Participant *mp_participant;
	Publisher *mp_fast_publisher;
	Publisher *mp_slow_publisher;

	class PubListener : public PublisherListener
	{
	public:
		PubListener() : n_matched(0){};
		~PubListener(){};
		void onPublicationMatched(Publisher* pub,MatchingInfo& info);
		int n_matched;
	} m_listener;
	FilteringExamplePubSubType myType;
};

#endif // _FILTERINGEXAMPLE_PUBLISHER_H_
