name: 'install-apt-packages-documentation'
description: 'Install necessary apt packages for building documentation'
runs:
  using: "composite"
  steps:
    - id: install-apt-packages-documentation
      run: |
        sudo apt -y install \
          gcc \
          g++ \
          cmake \
          libssl-dev \
          # Fast DDS documentation dependencies
          git \
          doxygen \
          doc8 \
          python3-venv \
          imagemagick \
          plantuml
      shell: bash
