name: 'install-apt-packages-documentation'
description: 'Install necessary apt packages for building documentation'
runs:
  using: "composite"
  steps:
    - id: install-apt-packages-documentation
      run: |
        sudo apt-get update
        sudo apt-get -y install \
          doxygen \
          imagemagick \
          plantuml
      shell: bash
