name: Install GTest
description: Install and setup GTest for linking and building test application
runs:
  using: composite
  steps:
  - run: sudo apt install googletest
    shell: bash
  - run: |
      mkdir gtest-build
      cd gtest-build
      cmake /usr/src/googletest
      sudo make install
      cd ..
      rm -rf gtest-build
    shell: bash
