name: get-ccache
description: "Get ccache (Ubuntu)"

inputs:
  ccache-folder:
    description: "Path to the folder where ccache cache is located"
    required: true

runs:
  using: 'composite'
  steps:

    - name: Install APT dependencies
      uses: eProsima/eProsima-CI/ubuntu/install_apt_packages@v0
      with:
        packages: curl
        update: false
        upgrade: false

    - name: Install latest version of CCache
      id: install-latest-ccache
      run: |
        set -e
        mkdir /opt/ccache
        cd /opt/ccache
        mkdir -p bin
        LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/ccache/ccache/releases/latest); \
        LATEST_VERSION=$(echo $LATEST_RELEASE | sed -e 's/.*"tag_name":"v\([^"]*\)".*/\1/'); \
        THRESHOLD="4.13"
        if [ "$(printf '%s\n%s' "$THRESHOLD" "$LAST_VERSION" | sort -V | head -n1)" = "$THRESHOLD" ]; then
          curl -OL https://github.com/ccache/ccache/releases/download/v$LATEST_VERSION/ccache-$LATEST_VERSION-linux-x86_64-glibc.tar.xz && \
          tar xf ccache-$LATEST_VERSION-linux-x86_64-glibc.tar.xz --strip-components=1 --one-top-level=bin
        else
          curl -OL https://github.com/ccache/ccache/releases/download/v$LATEST_VERSION/ccache-$LATEST_VERSION-linux-x86_64.tar.xz && \
          tar xf ccache-$LATEST_VERSION-linux-x86_64.tar.xz --strip-components=1 --one-top-level=bin
        fi
      shell: bash

    - name: Add CCache to PATH variable to env context
      id: add-ccache-path-env
      run: |
        echo "PATH=${{ env.WORKSPACE }}/opt/ccache/bin:$PATH" >> $GITHUB_ENV
        # echo "CCACHE_COMPILERCHECK=content" >> $GITHUB_ENV
        echo "CCACHE_BASEDIR=${{ env.WORKSPACE }}" >> $GITHUB_ENV
        echo "CCACHE_DIR=${{ inputs.ccache-folder }}" >> $GITHUB_ENV
      shell: bash

    - name: Check CCache
      id: check-ccache-version
      run: |
        ccache --version
        ccache --zero-stats || true
        ccache --show-stats || true
      shell: bash
