# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_BUNDLE "")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_DEB "")
set(CPACK_BINARY_DRAGNDROP "")
set(CPACK_BINARY_FREEBSD "")
set(CPACK_BINARY_IFW "")
set(CPACK_BINARY_NSIS "")
set(CPACK_BINARY_NUGET "")
set(CPACK_BINARY_OSXX11 "")
set(CPACK_BINARY_PACKAGEMAKER "")
set(CPACK_BINARY_PRODUCTBUILD "")
set(CPACK_BINARY_RPM "")
set(CPACK_BINARY_STGZ "")
set(CPACK_BINARY_TBZ2 "")
set(CPACK_BINARY_TGZ "")
set(CPACK_BINARY_TXZ "")
set(CPACK_BINARY_TZ "")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BUILD_SOURCE_DIRS "C:/Users/MiguelBarro/Documents/Fast-RTPS;C:/Users/MiguelBarro/Documents/Fast-RTPS/build64")
set(CPACK_CMAKE_GENERATOR "Visual Studio 15 2017 Win64")
set(CPACK_COMPONENTS_ALL "headers;licenses;libraries_x64Win64VS2017;cmake")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_CMAKE_HIDDEN "1")
set(CPACK_COMPONENT_HEADERS_DESCRIPTION "eProsima Fast RTPS C++ Headers")
set(CPACK_COMPONENT_HEADERS_DISPLAY_NAME "C++ Headers")
set(CPACK_COMPONENT_LIBRARIES_DESCRIPTION "eProsima Fast RTPS libraries")
set(CPACK_COMPONENT_LIBRARIES_DISPLAY_NAME "Libraries")
set(CPACK_COMPONENT_LICENSES_HIDDEN "1")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_GENERATOR "NSIS")
set(CPACK_INSTALL_CMAKE_PROJECTS "C:/Users/MiguelBarro/Documents/Fast-RTPS/build64;fastrtps;ALL;/")
set(CPACK_INSTALL_PREFIX "C:/Program Files/fastrtps")
set(CPACK_MODULE_PATH "C:/Users/MiguelBarro/Documents/Fast-RTPS/cmake/modules;C:/Users/MiguelBarro/Documents/Fast-RTPS/cmake/packaging/windows")
set(CPACK_NSIS_DISPLAY_NAME "fastrtps 1.7.1")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_PACKAGE_NAME "fastrtps 1.7.1")
set(CPACK_OUTPUT_CONFIG_FILE "C:/Users/MiguelBarro/Documents/Fast-RTPS/build64/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "eProsima Support <support@eprosima.com>")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "eProsima Fast RTPS library provides publication/subscription communication using RTPS protocol.")
set(CPACK_PACKAGE_DESCRIPTION_FILE "C:/Program Files/CMake/share/cmake-3.13/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "fastrtps - C++ library implementation of RTPS protocol")
set(CPACK_PACKAGE_FILE_NAME "fastrtps-1.7.1-win64")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "fastrtps 1.7.1")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "fastrtps 1.7.1")
set(CPACK_PACKAGE_NAME "fastrtps")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "eProsima")
set(CPACK_PACKAGE_VERSION "1.7.1")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "7")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_PROJECT_CONFIG_FILE "C:/Users/MiguelBarro/Documents/Fast-RTPS/build64/cmake/packaging/windows/WindowsPackaging.cmake")
set(CPACK_RESOURCE_FILE_LICENSE "C:/Users/MiguelBarro/Documents/Fast-RTPS/LICENSE")
set(CPACK_RESOURCE_FILE_README "C:/Program Files/CMake/share/cmake-3.13/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "C:/Program Files/CMake/share/cmake-3.13/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "ON")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_GENERATOR "7Z;ZIP")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "C:/Users/MiguelBarro/Documents/Fast-RTPS/build64/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "")
set(CPACK_SOURCE_TBZ2 "")
set(CPACK_SOURCE_TGZ "")
set(CPACK_SOURCE_TXZ "")
set(CPACK_SOURCE_TZ "")
set(CPACK_SOURCE_ZIP "ON")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_TOPLEVEL_TAG "win64")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "C:/Users/MiguelBarro/Documents/Fast-RTPS/build64/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
