module TrialModule
{
    module BitmaskModule
    {
        @bit_bound(8)
        bitmask BitmaskType
        {
            FLAG_ONE,
            FLAG_TWO,
            FLAG_THREE
        };
    };
};

struct TrialStruct
{
    TrialModule::BitmaskModule::BitmaskType bitmask_member;
};
