name: 'fetch-fastdds-repos'
description: 'Fetch Fast DDS dependencies'
runs:
  using: "composite"
  steps:
    - id: fetch-fastdds-repos
      run: |
        cd src
        git clone https://github.com/eProsima/foonathan_memory_vendor.git
        git clone https://github.com/eProsima/Fast-CDR.git
        git clone https://github.com/google/googletest.git --branch release-1.10.0
        cd ..
      shell: bash
