name: 'fetch-fastdds-repos'
description: 'Fetch Fast DDS dependencies'
inputs:
  target_directory:
    description: 'Target directory where the dependencies will be downloaded.'
    required: true
    default: '.'
  googletest:
    description: 'Specifies if GoogleTest repository should be downloaded.'
    required: false
    default: 'false'
  discovery_server:
    description: 'Specifies if Discovery Server repository should be downloaded.'
    required: false
    default: 'false'
  discovery_server_branch:
    description: 'Specifies Discovery Server branch. The final branch is calculated based on the event that triggers
      the action. Thus, if the action has been triggered as a result of a Pull Request, the branch will be the source
      branch, the target branch, "master", or the branch specified in this parameter.'
    required: false
    default: 'master'
runs:
  using: "composite"
  steps:
    - name: Fetch eProsima dependencies
      run: |
        git clone https://github.com/eProsima/foonathan_memory_vendor.git ${{ inputs.target_directory }}/foonathan_memory_vendor
        git clone https://github.com/eProsima/Fast-CDR.git ${{ inputs.target_directory }}/fastcdr
      shell: bash

    - name: Fetch GoogleTest
      if: ${{ inputs.googletest == 'true' }}
      run: git clone https://github.com/google/googletest.git --branch release-1.12.1 ${{ inputs.target_directory }}/googletest
      shell: bash

    - name: Fetch Discovery Server
      if: ${{ inputs.discovery_server == 'true' }}
      run: |
        base_dir=${PWD}
        git clone https://github.com/eProsima/Discovery-Server.git ${{ inputs.target_directory }}/discovery_server
        cd ${{ inputs.target_directory }}/discovery_server

        if [[ $(git rev-parse --verify "${{ github.head_ref }}" 2>/dev/null) ]]; then
          git checkout ${{ github.head_ref }}
        elif [[ $(git rev-parse --verify "${{ github.base_ref }}" 2>/dev/null) ]]; then
          git checkout ${{ github.base_ref }}
        else
          git checkout ${{ inputs.discovery_server_branch }}
        fi

        cd ${base_dir}
      shell: bash
