/* Copyright(C) 2025, Proyectos y Sistemas de Mantenimiento SL(eProsima)
 *
 * This program is commercial software licensed under the terms of the
 * eProsima Software License Agreement Rev 03 (the "License")
 *
 * You may obtain a copy of the License at
 * https://www.eprosima.com/licenses/LICENSE-REV03
 */

#ifndef FASTDDS_RTPS_TRANSPORT_LOWBANDWIDTH_SOURCETIMESTAMPTRANSPORT_HPP
#define FASTDDS_RTPS_TRANSPORT_LOWBANDWIDTH_SOURCETIMESTAMPTRANSPORT_HPP

#include <mutex>

#include <fastdds/rtps/transport/ChainingTransport.hpp>
#include <fastdds/rtps/transport/low-bandwidth/SourceTimestampTransportDescriptor.hpp>

namespace eprosima {
namespace fastdds {
namespace rtps {

/**
 * This transport will prepend a short (5 bytes) header to every packet, transmitting the timestamp seconds of the sender.
 * It will extract that information upon reception, and then invoke a callback informing of the timestamp (in seconds) of
 * the sender and the current timestamp of the receiver.
 * This callback and its generic parameter should be configured on the transport descriptor.
 * @ingroup TRANSPORT_MODULE
 */
class SourceTimestampTransport : public ChainingTransport
{

public:

    SourceTimestampTransport(
            const SourceTimestampTransportDescriptor&);

    ~SourceTimestampTransport() override;

    bool init(
            const fastdds::rtps::PropertyPolicy* properties = nullptr,
            const uint32_t& max_msg_size_no_frag = 0) override;

    TransportDescriptorInterface* get_configuration() override
    {
        return &configuration_;
    }

    /**
     * Blocking Send through the specified channel. It will prepend the timestamp information and then send the
     * data to the lower transport.
     * @param low_sender_resource SenderResource generated by the lower transport.
     * @param buffers Slice into the raw data to send.
     * @param send_buffer_size Size of the raw data. It will be used as a bounds check for the previous argument.
     * It must not exceed the sendBufferSize fed to this class during construction.
     * @param destination_locators_begin First iterator of the list of Locators describing the remote destinations
     * we're sending to.
     * @param destination_locators_end End iterator of the list of Locators describing the remote destinations
     * we're sending to.
     */
    bool send(
            fastdds::rtps::SenderResource* low_sender_resource,
            const std::vector<NetworkBuffer>& buffers,
            uint32_t send_buffer_size,
            fastdds::rtps::LocatorsIterator* destination_locators_begin,
            fastdds::rtps::LocatorsIterator* destination_locators_end,
            const std::chrono::steady_clock::time_point& timeout) override;

    /**
     * Blocking Send through the specified channel. It will prepend the timestamp information and then send the
     * data to the lower transport.
     * @param low_sender_resource SenderResource generated by the lower transport.
     * @param buffers Slice into the raw data to send.
     * @param send_buffer_size Size of the raw data. It will be used as a bounds check for the previous argument.
     * It must not exceed the sendBufferSize fed to this class during construction.
     * @param destination_locators_begin First iterator of the list of Locators describing the remote destinations
     * we're sending to.
     * @param destination_locators_end End iterator of the list of Locators describing the remote destinations
     * we're sending to.
     * @param timeout Maximum blocking time.
     */
    bool send_w_priority(
            fastdds::rtps::SenderResource* low_sender_resource,
            const std::vector<NetworkBuffer>& buffers,
            uint32_t send_buffer_size,
            fastdds::rtps::LocatorsIterator* destination_locators_begin,
            fastdds::rtps::LocatorsIterator* destination_locators_end,
            const std::chrono::steady_clock::time_point& timeout,
            int32_t transport_priority) override;

    /**
     * Blocking Receive from the specified channel. It will extract the timestamp information and perform
     * the callback invocation.
     * @param receiveBuffer vector with enough capacity (not size) to accomodate a full receive buffer. That
     * capacity must not be less than the receiveBufferSize supplied to this class during construction.
     * @param localLocator Locator mapping to the local channel we're listening to.
     * @param[out] remoteLocator Locator describing the remote restination we received a packet from.
     */
    void receive(
            TransportReceiverInterface* next_receiver,
            const fastdds::rtps::octet* receive_buffer,
            uint32_t receive_buffer_size,
            const fastdds::rtps::Locator_t& local_locator,
            const fastdds::rtps::Locator_t& remote_locator) override;

protected:

    //! Transport configuration including callback and buffer size
    SourceTimestampTransportDescriptor configuration_;
    //! Only one thread should have access to the compression buffer
    mutable std::recursive_mutex compress_buffer_mutex_;
    //! Compression buffer
    fastdds::rtps::octet* compress_buffer_ {nullptr};
    //! Assembly buffer
    fastdds::rtps::octet* assembly_buffer_ {nullptr};
};

} // namespace rtps
} // namespace fastdds
} // namespace eprosima

#endif // FASTDDS_RTPS_TRANSPORT_LOWBANDWIDTH_SOURCETIMESTAMPTRANSPORT_HPP
