//******** Std_msgs structures ********//
struct Timestamp {
  unsigned long long sec;
  unsigned long nanosec;
};

struct Header {
  long sec;
  unsigned long nanosec;
  string<256> frame_id;
};

//******** Sensor_msgs structures ********//
struct Image {
  Header header_value;
  unsigned long height;
  unsigned long width;
  string<256> encoding;
  boolean is_bigendian;
  unsigned long step;
  sequence<octet, 3840 * 2160 * 3> data; // Provisioning for 4K images
};

const octet PointField__INT8 = 1;
const octet PointField__UINT8 = 2;
const octet PointField__INT16 = 3;
const octet PointField__UINT16 = 4;
const octet PointField__INT32 = 5;
const octet PointField__UINT32 = 6;
const octet PointField__FLOAT32 = 7;
const octet PointField__FLOAT64 = 8;

struct PointField {
    string<256> name;
    unsigned long offset;
    octet datatype;
    unsigned long count;
};

struct PointCloud2 {
  Header header_value;
  unsigned long height;
  unsigned long width;
  sequence<PointField, 256> fields;
  boolean is_bigendian;
  unsigned long point_step;
  unsigned long row_step;
  sequence<octet, 4 * 4 * 4 * 1920 * 1080> data;
  boolean is_dense;
};

//******** BigData structure ********//
struct BigData {
  Timestamp timestamp_value;
  Image image_value;
  PointCloud2 point_cloud_value;
  unsigned long index;
};
