@extensibility(APPENDABLE)
enum CalculatorOperationType
{
    ADDITION,
    SUBTRACTION,
    MULTIPLICATION,
    DIVISION
};

@extensibility(APPENDABLE)
struct ClientID
{
    octet value[12];
};

@extensibility(APPENDABLE)
struct CalculatorRequestType
{
    @key ClientID client_id;
    CalculatorOperationType operation;
    short x;
    short y;
};

@extensibility(APPENDABLE)
struct CalculatorReplyType
{
    @key ClientID client_id;
    long z;
};
