name: 'install-apt-packages'
description: 'Install necessary apt packages'
runs:
  using: "composite"
  steps:
    - id: install-apt-packages
      run: |
        sudo apt-get update
        sudo apt-get -y install \
          curl \
          grep \
          libasio-dev \
          libtinyxml2-dev \
          python3 \
          python3-pip \
          software-properties-common \
          wget
      shell: bash
