# TINYXML2_FOUND
# TINYXML2_INCLUDE_DIR
# TINYXML2_SOURCE_DIR

find_path(TINYXML2_INCLUDE_DIR NAMES tinyxml2.h)
find_path(TINYXML2_SOURCE_DIR NAMES tinyxml2.cpp)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(tinyxml2 DEFAULT_MSG TINYXML2_SOURCE_DIR TINYXML2_INCLUDE_DIR)

mark_as_advanced(TINYXML2_INCLUDE_DIR TINYXML2_SOURCE_DIR)
