on: push

jobs:
  build_fastdds:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: bazelbuild/setup-bazelisk@v2
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: "${{ hashFiles('WORKSPACE') }}-${{ hashFiles('**/BUILD')}}"
    - run: bazel build //:fastdds
