name: Fast DDS Linters CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  uncrustify:
    name: uncrustify
    runs-on:
      - self-hosted
      - linux
      - x64
      - Ubuntu
    container:
      image: 'ci.intranet.eprosima.com:5000/eprosima/ubuntu-ci:noble'
    if: ${{ !(github.event_name == 'pull_request') || !contains(github.event.pull_request.labels.*.name, 'conflicts') }}
    steps:

      - name: Run Uncrustify Linter
        uses: eProsima/eProsima-CI/ubuntu/uncrustify@v0
        with:
          venv_path: /vdev

      - name: Clean workspace
        run: |
          find ${{ env.WORKSPACE }} -mindepth 1 -maxdepth 1 ! -name src -exec rm -rf -- {} +
        if: ${{ always() }}

