name: Fast DDS Windows CI (nightly)

on:
  pull_request:
    types:
      - review_requested
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '!**/CMakeLists.txt'

jobs:
  nightly-windows-ci-fix22592:
    name: nightly-windows-ci-fix22592 (${{ matrix.cmake_build_type }}, SEC=${{ matrix.security }}, ${{ matrix.test_filter }})
    strategy:
      fail-fast: false
      matrix:
        cmake_build_type:
          - 'RelWithDebInfo'
          - 'Debug'
        security:
          - 'ON'
          - 'OFF'
        test_filter:
          - 'blackbox'
          - 'unittest'
        filter_expression:
          - 'BlackboxTests|example_tests|ParticipantTests|SecureDiscoverServer'
    uses: eProsima/Fast-DDS/.github/workflows/reusable-windows-ci.yml@fix/22592
    with:
      label: nightly-sec-${{ matrix.security }}-${{ matrix.cmake_build_type }}-${{ matrix.test_filter }}-windows-ci-fix22592
      cmake-config: ${{ matrix.cmake_build_type }}
      cmake-args: "-DSECURITY=${{ matrix.security }}"
      ctest-args: -LE xfail ${{ matrix.test_filter == 'blackbox' && format('-R "{0}"', matrix.filter_expression) || format('-E "{0}" -j 4', matrix.filter_expression) }}
      fastdds_branch: 'fix/22592'
