name: Fast DDS Windows CI (nightly)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  nightly-windows-ci-2_14_x:
    strategy:
      fail-fast: false
      matrix:
        security:
          - 'ON'
          - 'OFF'
    uses: eProsima/Fast-DDS/.github/workflows/reusable-windows-ci.yml@2.14.x
    with:
      label: 'nightly-sec-${{ matrix.security }}-windows-ci-2.14.x'
      cmake-args: "-DSECURITY=${{ matrix.security }}"
      ctest-args: "-LE xfail"
      fastdds_branch: '2.14.x'
