name: Fast DDS Ubuntu CI (weekly)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Run at minute 0 on Monday

jobs:

  weekly-ubuntu-ci-2_14_x:
    strategy:
      fail-fast: false
      matrix:
        fastcdr-branch:
          - '1.1.x'
          - '2.x'
        security:
          - true
          - false
    uses: eProsima/Fast-DDS/.github/workflows/reusable-ubuntu-ci.yml@2.14.x
    with:
      os-image: 'ubuntu-22.04'
      label: 'weekly-sec-${{ matrix.security }}-fastcdr-${{ matrix.fastcdr-branch }}-ubuntu-ci-2.14.x'
      ctest-args: "-LE xfail"
      fastdds-branch: '2.14.x'
      fastcdr-branch: ${{ matrix.fastcdr-branch }}
      security: ${{ matrix.security }}
      run-build: true
      run-tests: true
      use-ccache: false

  weekly-ubuntu-ci-2_6_x:
    strategy:
      fail-fast: false
      matrix:
        security:
          - true
          - false
    uses: eProsima/Fast-DDS/.github/workflows/reusable-ubuntu-ci.yml@2.6.x
    with:
      os-image: 'ubuntu-20.04'
      label: 'weekly-sec-${{ matrix.security }}-ubuntu-ci-2.6.x'
      ctest-args: "-LE xfail"
      fastdds-branch: '2.6.x'
      security: ${{ matrix.security }}
      run-build: true
      run-tests: true
      use-ccache: false
